services:
  app:
    image: the-balance:latest
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./sqlite.db:/app/sqlite.db
    command: ["node", ".output/server/index.mjs"]
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs
    depends_on:
      - app
